<a href="https://colab.research.google.com/github/aglie/iucr2020_compschool/blob/main/arkadiy_eigenvalues_101/Tutorial_1_matrices%2C_vectors%2C_calcualte_eigenvalue.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


# Task 1: Calculate largest eigenvector by repeated matrix multiplication

Below is a 3x3 symmetric matrix $A$, find its highest eigenvector by repeatedly applying it to any starting vector $v$. 

$$
h_1 = A^n v
$$


In [ ]:
A = array([[2, 1, 1], 
           [1, 3, 2],
           [1, 2, 3]])

In [ ]:
h1 = [1, 0, 0] #a starting vector
N = 100 #number of iterations

for i in range(N):
  #write your code here

# Solution

In [ ]:
h1 = [1, 0, 0] #a starting vector
N = 100 #number of iterations

for i in range(N):
  h1 = dot(A, h) # calcualte new guess for h as a matrix multiplication Ah 
  h1 = h/norm(h) # normalize h not to overflow doubles
h1

array([0.36905132, 0.65719142, 0.65719142])

In [ ]:
lam1 = dot(h1, dot(A,h1)) # eigenvalue associated with this eigenvector
lam1

5.561552812761904

# Task 2$^*$: calculate the second eigenvector
Now that the first eigenvector is known, you can calculate the second largest eigenvector by projecting out the components of the first one:

$$
h_2 = AP[AP[...AP[v]]
$$

Where $P$ is an operator which projects out components of the vector $h_1$ using scalar product $(vh_1)$:

$$
P[v] = v - h_1 (vh_1)
$$


In [ ]:
h2 = [1,0,0]

for i in range(100):
  ... #Write your code here

## Solution

In [ ]:
h2 = [1,0,0]

for i in range(100):
  h2 = h2 - h1*dot(h1, h2) #project h1 out
  h2 = dot(A, h2) #apply A
  h2 = h2/norm(h2) #normalize not to overflow

h2

array([ 0.92940545, -0.26096505, -0.26096505])

In [ ]:
lam2 = dot(h2, dot(A,h2))
lam2

1.438447187892681

# Calculation of eigenvalues and eigenfunctions using `eig`

Now let's calculate the same eigenvectors and eigenfunctions using the function `eig` from the package `numpy.linalg`, compare those with your results.

Note that in practice you will almost never diagonalize a small matrix using the iterative approach that we have implemented. This approach, though, is very useful when you need to calculate just a few eigenvalues and eigenvectors for a matrix which is too large to fit in computer memory. 

In [ ]:
lam, vec = eig(A)
lam

array([1.43844719, 5.56155281, 1.        ])

In [ ]:
vec

array([[-9.29410263e-01,  3.69048184e-01,  1.94927723e-16],
       [ 2.60956474e-01,  6.57192300e-01, -7.07106781e-01],
       [ 2.60956474e-01,  6.57192300e-01,  7.07106781e-01]])

# Task 3:

What is the eigenvector with the smallest eigenvalue?

In [ ]:
vec3 = ...
lam3 = ...

## Solution

In [ ]:
lam, vec = eig(A)

lam3 = amin(lam) # eig doesn't sort eigenvalues, so we need to find the smallest one
lam3

1.0

In [ ]:
h3 = vec[:, argmin(lam)] # eigenvectors are arranged as column-vectors in h3
h3

array([ 1.94927723e-16, -7.07106781e-01,  7.07106781e-01])

In [ ]:
#check that we have done everything correctly

dot(h3, dot(A, h3))

1.0000000000000002